### ISSUE TITLE
Capsule collision doesn't work with some triangle meshes

### ISSUE THREAD

**Issue by eliasdaler** [SolarLune/tetra3d#27]
See repro here: https://github.com/eliasdaler/Tetra3d/tree/bounds_issues/examples/bounds

When trying to climb a new surface I added with a capsule, collision doesn't work properly and the capsule doesn't ascend.

**Comment by SolarLune** [comment]
Hello, thanks for the report; I've solved this with the last commit (44544eecca2c9fdf776e0dd0e0d9761c1aff1784). Pulling that should resolve the issue for you.

**Comment by eliasdaler** [comment]
Can confirm, that fixes the issue, thanks!
I still have some issues with collisions at certain parts (e.g. spheres shaking a bit when rolling over completely flat surfaces) - once I find the repro, I'll open another issue.
